# Generated by Django 4.2.1 on 2023-06-06 18:09

import app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(max_length=128)),
            ],
            options={
                "verbose_name": "Director",
                "verbose_name_plural": "Directors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(max_length=128)),
                (
                    "year",
                    models.IntegerField(
                        null=True,
                    ),
                ),
                ("directors", models.ManyToManyField(to="app.director")),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["year", "title"],
            },
        ),
    ]
